python -m Mean_Teacher.clf.main \
--model bert \
--data_folder Data/ExperimentFolds/3 \
--data fakehealth \
--model_output_folder trained_models \
--pretrained_model bert-base-uncased \
--max_len 512 \
--dropout 0.5 \
--epochs 1 \
--batch_size 2 \
--lr 2e-5 \
--seed 42