python -m src.main \
--pretrained_model distilbert-base-uncased \
--data_folder 'Data/ExperimentFolds/3' \
--data fakehealth \
--model_output_folder trained_models \
--model bert \
--max_len 300 \
--dropout 0.1 \
--batch_size 8 \
--lr 2e-5 \
--seed 42 \
--do_train \
--epochs 3 \
--ratio_label 1.0
